[profile.default]
src = 'contracts'
out = 'foundry-out'
libs = ['lib']
auto_detect_solc = true
optimizer_runs = 800
via_ir = true
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}, { access = "read", path = "./foundry-out"}]

[profile.ci]
fuzz_runs = 100000
